apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: moncfgs.monitoring.pf9.io
spec:
  group: monitoring.pf9.io
  names:
    kind: MonCfg
    listKind: MonCfgList
    plural: moncfgs
    singular: moncfg
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
