apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mon-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups:
  - monitoring.pf9.io
  resources:
  - moncfgs
  verbs:
  - '*'

